version: "3"

services:
  client:
    build:
      network: host
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    depends_on:
      - server
    environment:
      - API_BASE_URL=http://localhost:8081
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true

  server:
    build:
      network: host
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./server/src:/usr/app/src
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/mongo
  test:
    build:
      context: ./client
    environment:
      - CI=true
    command: npm test
volumes:
  mongo-data:
    driver: local
